nginx:
    build: ./nginx
    volumes:
        - .:/usr/src/app
    links:
        - django
    ports:
        - "80:80"

django:
    build: .
    volumes:
        - .:/usr/src/app
    expose:
        - "8000"
